version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_1_29"
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: library/mysql:5.7
    container_name: "MySQL_Database_1_29"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro